design_config:
  name: "design"
  using_primary: False
  using_secondary: True
  using_harvester: True
  operating_voltage_V: 3
  boost_efficiency: 0.85
  frontend_efficiency: 0.9

secondary_config:
  type: "capacitor"
  esr_ohm: 0.2
  leakage_power_W: 15.0E-6
  capacity_J: 720
  #!!python/object/apply:eval [ .5 * 33E-3 * (3**2) ]
  min_capacity_J: 0.02537
  #!!python/object/apply:eval [ .5 * 33E-3 * (1.24**2) ]

harvest_config:
  type: "solar"
  nominal_voltage: 3.4
  area_cm2: 6.16
  efficiency: 0.20
