/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Sun Nov 10 18:42:17 2019. */

#ifndef PB_PARSE_PB_H_INCLUDED
#define PB_PARSE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(16) Data_thread_ext_addr_t;
typedef struct _Data {
    char discovery[64];
    char version[64];
    float temperature_c;
    float pressure_mbar;
    float humidity_percent;
    float primary_voltage;
    float solar_voltage;
    float secondary_voltage;
    bool vbat_ok;
    float light_color_cct_k;
    uint32_t light_color_red;
    uint32_t light_color_green;
    uint32_t light_color_blue;
    uint32_t light_color_clear;
    float light_lux;
    bool motion;
    uint32_t thread_rloc16;
    Data_thread_ext_addr_t thread_ext_addr;
    uint32_t thread_parent_avg_rssi;
    uint32_t thread_parent_last_rssi;
/* @@protoc_insertion_point(struct:Data) */
} Data;

typedef PB_BYTES_ARRAY_T(64) Header_id_t;
typedef struct _Header {
    uint32_t version;
    Header_id_t id;
    uint32_t seq_no;
    uint64_t tv_sec;
    uint32_t tv_usec;
/* @@protoc_insertion_point(struct:Header) */
} Header;

typedef struct _Message {
    Header header;
    Data data;
/* @@protoc_insertion_point(struct:Message) */
} Message;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Header_init_default                      {0, {0, {0}}, 0, 0, 0}
#define Data_init_default                        {"", "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {0, {0}}, 0, 0}
#define Message_init_default                     {Header_init_default, Data_init_default}
#define Header_init_zero                         {0, {0, {0}}, 0, 0, 0}
#define Data_init_zero                           {"", "", 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {0, {0}}, 0, 0}
#define Message_init_zero                        {Header_init_zero, Data_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define Data_discovery_tag                       1
#define Data_version_tag                         2
#define Data_temperature_c_tag                   10
#define Data_pressure_mbar_tag                   11
#define Data_humidity_percent_tag                12
#define Data_primary_voltage_tag                 20
#define Data_solar_voltage_tag                   21
#define Data_secondary_voltage_tag               22
#define Data_vbat_ok_tag                         23
#define Data_light_color_cct_k_tag               30
#define Data_light_color_red_tag                 31
#define Data_light_color_green_tag               32
#define Data_light_color_blue_tag                33
#define Data_light_color_clear_tag               34
#define Data_light_lux_tag                       35
#define Data_motion_tag                          40
#define Data_thread_rloc16_tag                   50
#define Data_thread_ext_addr_tag                 51
#define Data_thread_parent_avg_rssi_tag          52
#define Data_thread_parent_last_rssi_tag         53
#define Header_version_tag                       1
#define Header_id_tag                            2
#define Header_seq_no_tag                        3
#define Header_tv_sec_tag                        4
#define Header_tv_usec_tag                       5
#define Message_header_tag                       1
#define Message_data_tag                         2

/* Struct field encoding specification for nanopb */
extern const pb_field_t Header_fields[6];
extern const pb_field_t Data_fields[21];
extern const pb_field_t Message_fields[3];

/* Maximum encoded size of messages (where known) */
#define Header_size                              95
#define Data_size                                251
#define Message_size                             351

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define PARSE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
