/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Thu Nov  7 10:12:05 2019. */

#ifndef PB_PARSE_PB_H_INCLUDED
#define PB_PARSE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(16) Data_thread_ext_addr_t;
typedef struct _Data {
    float temperature_c;
    float pressure_mbar;
    float humidity_percent;
    float primary_voltage;
    float solar_voltage;
    float secondary_voltage;
    bool vbat_ok;
    float light_color_cct_k;
    uint32_t light_color_red;
    uint32_t light_color_green;
    uint32_t light_color_blue;
    uint32_t light_color_clear;
    float light_lux;
    bool motion;
    char discovery[64];
    char version[64];
    uint32_t thread_rloc16;
    Data_thread_ext_addr_t thread_ext_addr;
    uint32_t thread_parent_avg_rssi;
    uint32_t thread_parent_last_rssi;
/* @@protoc_insertion_point(struct:Data) */
} Data;

typedef PB_BYTES_ARRAY_T(64) Header_id_t;
typedef struct _Header {
    uint32_t version;
    Header_id_t id;
    uint32_t seq_no;
    uint64_t tv_sec;
    uint32_t tv_usec;
/* @@protoc_insertion_point(struct:Header) */
} Header;

typedef struct _PermamoteMessage {
    Header header;
    Data data;
/* @@protoc_insertion_point(struct:PermamoteMessage) */
} PermamoteMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Header_init_default                      {0, {0, {0}}, 0, 0, 0}
#define Data_init_default                        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", "", 0, {0, {0}}, 0, 0}
#define PermamoteMessage_init_default            {Header_init_default, Data_init_default}
#define Header_init_zero                         {0, {0, {0}}, 0, 0, 0}
#define Data_init_zero                           {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "", "", 0, {0, {0}}, 0, 0}
#define PermamoteMessage_init_zero               {Header_init_zero, Data_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define Data_temperature_c_tag                   1
#define Data_pressure_mbar_tag                   2
#define Data_humidity_percent_tag                3
#define Data_primary_voltage_tag                 4
#define Data_solar_voltage_tag                   5
#define Data_secondary_voltage_tag               6
#define Data_vbat_ok_tag                         7
#define Data_light_color_cct_k_tag               8
#define Data_light_color_red_tag                 9
#define Data_light_color_green_tag               10
#define Data_light_color_blue_tag                11
#define Data_light_color_clear_tag               12
#define Data_light_lux_tag                       13
#define Data_motion_tag                          14
#define Data_discovery_tag                       15
#define Data_version_tag                         16
#define Data_thread_rloc16_tag                   30
#define Data_thread_ext_addr_tag                 31
#define Data_thread_parent_avg_rssi_tag          32
#define Data_thread_parent_last_rssi_tag         33
#define Header_version_tag                       1
#define Header_id_tag                            2
#define Header_seq_no_tag                        3
#define Header_tv_sec_tag                        4
#define Header_tv_usec_tag                       5
#define PermamoteMessage_header_tag              1
#define PermamoteMessage_data_tag                2

/* Struct field encoding specification for nanopb */
extern const pb_field_t Header_fields[6];
extern const pb_field_t Data_fields[21];
extern const pb_field_t PermamoteMessage_fields[3];

/* Maximum encoded size of messages (where known) */
#define Header_size                              95
#define Data_size                                241
#define PermamoteMessage_size                    341

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define PARSE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
