/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Sun Oct 13 16:26:01 2019. */

#include "permamote_message.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Header_fields[6] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, Header, version, version, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, STATIC  , OTHER, Header, id, version, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, Header, seq_no, id, 0),
    PB_FIELD(  4, UINT64  , SINGULAR, STATIC  , OTHER, Header, tv_sec, seq_no, 0),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, Header, tv_usec, tv_sec, 0),
    PB_LAST_FIELD
};

const pb_field_t SystemVoltage_fields[5] = {
    PB_FIELD(  1, FLOAT   , SINGULAR, STATIC  , FIRST, SystemVoltage, vbat, vbat, 0),
    PB_FIELD(  2, FLOAT   , SINGULAR, STATIC  , OTHER, SystemVoltage, vsol, vbat, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, SystemVoltage, vsec, vsol, 0),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, SystemVoltage, vbat_ok, vsec, 0),
    PB_LAST_FIELD
};

const pb_field_t ColorCounts_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, ColorCounts, red, red, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, ColorCounts, green, red, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, ColorCounts, blue, green, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, ColorCounts, clear, blue, 0),
    PB_LAST_FIELD
};

const pb_field_t ThreadInfo_fields[5] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, ThreadInfo, rloc16, rloc16, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, STATIC  , OTHER, ThreadInfo, ext_addr, rloc16, 0),
    PB_FIELD(  3, UINT32  , SINGULAR, STATIC  , OTHER, ThreadInfo, parent_avg_rssi, ext_addr, 0),
    PB_FIELD(  4, UINT32  , SINGULAR, STATIC  , OTHER, ThreadInfo, parent_last_rssi, parent_avg_rssi, 0),
    PB_LAST_FIELD
};

const pb_field_t SystemData_fields[4] = {
    PB_FIELD(  2, STRING  , SINGULAR, STATIC  , FIRST, SystemData, discovery, discovery, 0),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, SystemData, thread_info, discovery, &ThreadInfo_fields),
    PB_FIELD(  4, STRING  , SINGULAR, STATIC  , OTHER, SystemData, version, thread_info, 0),
    PB_LAST_FIELD
};

const pb_field_t SensorData_fields[9] = {
    PB_FIELD(  1, FLOAT   , SINGULAR, STATIC  , FIRST, SensorData, temperature_c, temperature_c, 0),
    PB_FIELD(  2, FLOAT   , SINGULAR, STATIC  , OTHER, SensorData, pressure_mbar, temperature_c, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, SensorData, humidity_percent, pressure_mbar, 0),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, SensorData, voltage, humidity_percent, &SystemVoltage_fields),
    PB_FIELD(  5, FLOAT   , SINGULAR, STATIC  , OTHER, SensorData, light_color_cct_k, voltage, 0),
    PB_FIELD(  6, MESSAGE , SINGULAR, STATIC  , OTHER, SensorData, light_color_counts, light_color_cct_k, &ColorCounts_fields),
    PB_FIELD(  7, FLOAT   , SINGULAR, STATIC  , OTHER, SensorData, light_lux, light_color_counts, 0),
    PB_FIELD(  8, BOOL    , SINGULAR, STATIC  , OTHER, SensorData, motion, light_lux, 0),
    PB_LAST_FIELD
};

const pb_field_t PermamoteMessage_fields[4] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, PermamoteMessage, header, header, &Header_fields),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, PermamoteMessage, sensor_data, header, &SensorData_fields),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, PermamoteMessage, system_data, sensor_data, &SystemData_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SystemData, thread_info) < 65536 && pb_membersize(SensorData, voltage) < 65536 && pb_membersize(SensorData, light_color_counts) < 65536 && pb_membersize(PermamoteMessage, header) < 65536 && pb_membersize(PermamoteMessage, sensor_data) < 65536 && pb_membersize(PermamoteMessage, system_data) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Header_SystemVoltage_ColorCounts_ThreadInfo_SystemData_SensorData_PermamoteMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SystemData, thread_info) < 256 && pb_membersize(SensorData, voltage) < 256 && pb_membersize(SensorData, light_color_counts) < 256 && pb_membersize(PermamoteMessage, header) < 256 && pb_membersize(PermamoteMessage, sensor_data) < 256 && pb_membersize(PermamoteMessage, system_data) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Header_SystemVoltage_ColorCounts_ThreadInfo_SystemData_SensorData_PermamoteMessage)
#endif


/* @@protoc_insertion_point(eof) */
