/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: permamote_message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "permamote_message.pb-c.h"
void   header__init
                     (Header         *message)
{
  static const Header init_value = HEADER__INIT;
  *message = init_value;
}
size_t header__get_packed_size
                     (const Header *message)
{
  assert(message->base.descriptor == &header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t header__pack
                     (const Header *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t header__pack_to_buffer
                     (const Header *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Header *
       header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Header *)
     protobuf_c_message_unpack (&header__descriptor,
                                allocator, len, data);
}
void   header__free_unpacked
                     (Header *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   system_voltages__init
                     (SystemVoltages         *message)
{
  static const SystemVoltages init_value = SYSTEM_VOLTAGES__INIT;
  *message = init_value;
}
size_t system_voltages__get_packed_size
                     (const SystemVoltages *message)
{
  assert(message->base.descriptor == &system_voltages__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t system_voltages__pack
                     (const SystemVoltages *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &system_voltages__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t system_voltages__pack_to_buffer
                     (const SystemVoltages *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &system_voltages__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SystemVoltages *
       system_voltages__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SystemVoltages *)
     protobuf_c_message_unpack (&system_voltages__descriptor,
                                allocator, len, data);
}
void   system_voltages__free_unpacked
                     (SystemVoltages *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &system_voltages__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   color_counts__init
                     (ColorCounts         *message)
{
  static const ColorCounts init_value = COLOR_COUNTS__INIT;
  *message = init_value;
}
size_t color_counts__get_packed_size
                     (const ColorCounts *message)
{
  assert(message->base.descriptor == &color_counts__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t color_counts__pack
                     (const ColorCounts *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &color_counts__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t color_counts__pack_to_buffer
                     (const ColorCounts *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &color_counts__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ColorCounts *
       color_counts__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ColorCounts *)
     protobuf_c_message_unpack (&color_counts__descriptor,
                                allocator, len, data);
}
void   color_counts__free_unpacked
                     (ColorCounts *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &color_counts__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   thread_info__init
                     (ThreadInfo         *message)
{
  static const ThreadInfo init_value = THREAD_INFO__INIT;
  *message = init_value;
}
size_t thread_info__get_packed_size
                     (const ThreadInfo *message)
{
  assert(message->base.descriptor == &thread_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t thread_info__pack
                     (const ThreadInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &thread_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t thread_info__pack_to_buffer
                     (const ThreadInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &thread_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ThreadInfo *
       thread_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ThreadInfo *)
     protobuf_c_message_unpack (&thread_info__descriptor,
                                allocator, len, data);
}
void   thread_info__free_unpacked
                     (ThreadInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &thread_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   system_data__init
                     (SystemData         *message)
{
  static const SystemData init_value = SYSTEM_DATA__INIT;
  *message = init_value;
}
size_t system_data__get_packed_size
                     (const SystemData *message)
{
  assert(message->base.descriptor == &system_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t system_data__pack
                     (const SystemData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &system_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t system_data__pack_to_buffer
                     (const SystemData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &system_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SystemData *
       system_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SystemData *)
     protobuf_c_message_unpack (&system_data__descriptor,
                                allocator, len, data);
}
void   system_data__free_unpacked
                     (SystemData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &system_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sensor_data__init
                     (SensorData         *message)
{
  static const SensorData init_value = SENSOR_DATA__INIT;
  *message = init_value;
}
size_t sensor_data__get_packed_size
                     (const SensorData *message)
{
  assert(message->base.descriptor == &sensor_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensor_data__pack
                     (const SensorData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensor_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensor_data__pack_to_buffer
                     (const SensorData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensor_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SensorData *
       sensor_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SensorData *)
     protobuf_c_message_unpack (&sensor_data__descriptor,
                                allocator, len, data);
}
void   sensor_data__free_unpacked
                     (SensorData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensor_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor header__field_descriptors[5] =
{
  {
    "path",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Header, path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Header, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq_no",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Header, seq_no),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tv_sec",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Header, tv_sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tv_usec",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Header, tv_usec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned header__field_indices_by_name[] = {
  1,   /* field[1] = id */
  0,   /* field[0] = path */
  2,   /* field[2] = seq_no */
  3,   /* field[3] = tv_sec */
  4,   /* field[4] = tv_usec */
};
static const ProtobufCIntRange header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Header",
  "Header",
  "Header",
  "",
  sizeof(Header),
  5,
  header__field_descriptors,
  header__field_indices_by_name,
  1,  header__number_ranges,
  (ProtobufCMessageInit) header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor system_voltages__field_descriptors[3] =
{
  {
    "vbat",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SystemVoltages, vbat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vsol",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SystemVoltages, vsol),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vsec",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SystemVoltages, vsec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned system_voltages__field_indices_by_name[] = {
  0,   /* field[0] = vbat */
  2,   /* field[2] = vsec */
  1,   /* field[1] = vsol */
};
static const ProtobufCIntRange system_voltages__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor system_voltages__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SystemVoltages",
  "SystemVoltages",
  "SystemVoltages",
  "",
  sizeof(SystemVoltages),
  3,
  system_voltages__field_descriptors,
  system_voltages__field_indices_by_name,
  1,  system_voltages__number_ranges,
  (ProtobufCMessageInit) system_voltages__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor color_counts__field_descriptors[4] =
{
  {
    "red",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ColorCounts, red),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "green",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ColorCounts, green),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blue",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ColorCounts, blue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clear",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ColorCounts, clear),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned color_counts__field_indices_by_name[] = {
  2,   /* field[2] = blue */
  3,   /* field[3] = clear */
  1,   /* field[1] = green */
  0,   /* field[0] = red */
};
static const ProtobufCIntRange color_counts__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor color_counts__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ColorCounts",
  "ColorCounts",
  "ColorCounts",
  "",
  sizeof(ColorCounts),
  4,
  color_counts__field_descriptors,
  color_counts__field_indices_by_name,
  1,  color_counts__number_ranges,
  (ProtobufCMessageInit) color_counts__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor thread_info__field_descriptors[2] =
{
  {
    "rloc16",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ThreadInfo, rloc16),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext_addr",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ThreadInfo, ext_addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned thread_info__field_indices_by_name[] = {
  1,   /* field[1] = ext_addr */
  0,   /* field[0] = rloc16 */
};
static const ProtobufCIntRange thread_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor thread_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ThreadInfo",
  "ThreadInfo",
  "ThreadInfo",
  "",
  sizeof(ThreadInfo),
  2,
  thread_info__field_descriptors,
  thread_info__field_indices_by_name,
  1,  thread_info__number_ranges,
  (ProtobufCMessageInit) thread_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor system_data__field_descriptors[4] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SystemData, header),
    &header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "discovery",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SystemData, discovery),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thread_info",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SystemData, thread_info),
    &thread_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SystemData, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned system_data__field_indices_by_name[] = {
  1,   /* field[1] = discovery */
  0,   /* field[0] = header */
  2,   /* field[2] = thread_info */
  3,   /* field[3] = version */
};
static const ProtobufCIntRange system_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor system_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SystemData",
  "SystemData",
  "SystemData",
  "",
  sizeof(SystemData),
  4,
  system_data__field_descriptors,
  system_data__field_indices_by_name,
  1,  system_data__number_ranges,
  (ProtobufCMessageInit) system_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sensor_data__field_descriptors[10] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SensorData, header),
    &header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temperature_c",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SensorData, temperature_c),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pressure_mbar",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SensorData, pressure_mbar),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "humidity_percent",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SensorData, humidity_percent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "voltage",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SensorData, voltage),
    &system_voltages__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vbat_ok",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(SensorData, vbat_ok),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "light_color_cct_k",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SensorData, light_color_cct_k),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "light_color_counts",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(SensorData, light_color_counts),
    &color_counts__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "light_lux",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(SensorData, light_lux),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "motion",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(SensorData, motion),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensor_data__field_indices_by_name[] = {
  0,   /* field[0] = header */
  3,   /* field[3] = humidity_percent */
  6,   /* field[6] = light_color_cct_k */
  7,   /* field[7] = light_color_counts */
  8,   /* field[8] = light_lux */
  9,   /* field[9] = motion */
  2,   /* field[2] = pressure_mbar */
  1,   /* field[1] = temperature_c */
  5,   /* field[5] = vbat_ok */
  4,   /* field[4] = voltage */
};
static const ProtobufCIntRange sensor_data__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 1 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor sensor_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SensorData",
  "SensorData",
  "SensorData",
  "",
  sizeof(SensorData),
  10,
  sensor_data__field_descriptors,
  sensor_data__field_indices_by_name,
  2,  sensor_data__number_ranges,
  (ProtobufCMessageInit) sensor_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
